version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    networks:
    - common

  message_store_mongodb:
    image: php_base:1.1
    volumes:
    - ..:/srv/app
    working_dir: /srv/app
    command: 'docker/wait-for-it.sh mongo:27017 -- vendor/phpunit/phpunit/phpunit tests'
    networks:
    - common

networks:
  common:
    driver: bridge
